# Generated by Django 2.1.2 on 2018-10-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTrades',
            fields=[
                ('ID', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Trade Id.')),
                ('sell_currency', models.CharField(max_length=3)),
                ('sell_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('buy_currency', models.CharField(max_length=3)),
                ('buy_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
