# Generated by Django 2.1.2 on 2018-10-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booked', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedtrades',
            options={'ordering': ['-date_booked'], 'verbose_name': 'Booked Trade', 'verbose_name_plural': 'Booked Trades'},
        ),
    ]
