# Generated by Django 2.1.2 on 2018-10-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booked', '0002_auto_20181003_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedtrades',
            name='buy_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Buy Amount'),
        ),
        migrations.AlterField(
            model_name='bookedtrades',
            name='buy_currency',
            field=models.CharField(max_length=3, verbose_name='Buy CCY'),
        ),
        migrations.AlterField(
            model_name='bookedtrades',
            name='date_booked',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Booked'),
        ),
        migrations.AlterField(
            model_name='bookedtrades',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='bookedtrades',
            name='sell_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Sell Amount'),
        ),
        migrations.AlterField(
            model_name='bookedtrades',
            name='sell_currency',
            field=models.CharField(max_length=3, verbose_name='Sell CCY'),
        ),
    ]
